/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.sebsa;

import dk.sebsa.mana.LogFormatter;
import dk.sebsa.mana.Logger;
import dk.sebsa.mana.impl.FormatBuilder;
import dk.sebsa.mana.impl.FormatterImpl;
import dk.sebsa.mana.impl.PrintStreamLogger;

import java.io.IOException;

public class Sandbox {
    private final Logger logger;

    public Sandbox() throws IOException {
        LogFormatter formatter = new FormatBuilder().buildFromFile("/Format.xml");
        logger = new PrintStreamLogger(System.out, formatter);
    }

    private void run() {
        Mana.logSystemInfo(logger);
    }

    public static void main(String[] args) {
        try {
            new Sandbox().run();
        } catch (IOException e) {
            System.out.println("Program crashed without unhandled exception.");
        }
    }
}
