name: Gradle Build & Publish

on:
  push:
    branches: [ "main" ]

jobs:
  gradle-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build & Publish with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.REPOSILITE_NAME }}
          MAVEN_PASSWORD: ${{ secrets.REPOSILITE_SECRET }}
        run: ./gradlew clean build publish